#:schema node_modules/wrangler/config-schema.json
name = "bike-santiago-dev"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
STRAVA_API_URL = "https://www.strava.com/api/v3"
STRAVA_LONGEST_ACTIVITY_ID = "6569620057"

[[kv_namespaces]]
binding = "KV"
id = "5c6c326e5af443d6850449929809a90c"
preview_id = "5c6c326e5af443d6850449929809a90c"