name = "santiago-bike-stats"
type = "javascript"
workers_dev = true

account_id = "74d25d8b7fbbb58acbba3cafeb425477"

kv_namespaces = [ 
	 { binding = "BIKE_STATS", preview_id = "dbce2905240e45788aac9e350385bf40", id = "82f36137d7724171b3fe55051a7ec910" }
]

[env.production]
zone_id = "d7be1803f898c81c9e59cacb67a07e53"

route = "santiago.bike/stats"